/** Ações rastreadas pela auditoria. */
export enum AcaoAuditoria {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FALHOU = 'LOGIN_FALHOU',

  UPLOAD_INICIADO = 'UPLOAD_INICIADO',
  UPLOAD_CONCLUIDO = 'UPLOAD_CONCLUIDO',
  UPLOAD_FALHOU = 'UPLOAD_FALHOU',

  GRUPO_CRIADO = 'GRUPO_CRIADO',
  GRUPO_ALTERADO = 'GRUPO_ALTERADO',
  GRUPO_EXCLUIDO = 'GRUPO_EXCLUIDO',
  PARTICIPANTE_INCLUIDO = 'PARTICIPANTE_INCLUIDO',
  PARTICIPANTE_REMOVIDO = 'PARTICIPANTE_REMOVIDO',
  PARTICIPANTE_ATUALIZADO = 'PARTICIPANTE_ATUALIZADO',

  COMITE_CRIADO = 'COMITE_CRIADO',
  COMITE_ALTERADO = 'COMITE_ALTERADO',
  COMITE_EXCLUIDO = 'COMITE_EXCLUIDO',
  COMITE_APROVADO = 'COMITE_APROVADO',
  COMITE_FINALIZADO = 'COMITE_FINALIZADO',

  DISCRICIONARIO_CRIADO = 'DISCRICIONARIO_CRIADO',
  DISCRICIONARIO_ALTERADO = 'DISCRICIONARIO_ALTERADO',
  DISCRICIONARIO_REMOVIDO = 'DISCRICIONARIO_REMOVIDO',
  JUSTIFICATIVA_ALTERADA = 'JUSTIFICATIVA_ALTERADA',
  AVALIACAO_COMPORTAMENTAL_ALTERADA = 'AVALIACAO_COMPORTAMENTAL_ALTERADA',
  ANALISE_ATUALIZADA = 'ANALISE_ATUALIZADA',

  FILTRO_APLICADO = 'FILTRO_APLICADO',
  CONSULTA_REALIZADA = 'CONSULTA_REALIZADA',
  ERRO_PROCESSAMENTO = 'ERRO_PROCESSAMENTO',
  ACAO_FRONTEND = 'ACAO_FRONTEND',
}

/** De onde partiu o registro de auditoria. */
export enum OrigemAuditoria {
  BACKEND = 'BACKEND',
  FRONTEND = 'FRONTEND',
}
