/** Ações rastreadas pela trilha de auditoria (seção 8 — AuditLog). */
export enum AcaoAuditoria {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FALHOU = 'LOGIN_FALHOU',

  CICLO_CRIADO = 'CICLO_CRIADO',
  CICLO_ATIVADO = 'CICLO_ATIVADO',
  CICLO_FECHADO = 'CICLO_FECHADO',
  CICLO_REABERTO = 'CICLO_REABERTO',
  PREMISSA_ALTERADA = 'PREMISSA_ALTERADA',

  UPLOAD_INICIADO = 'UPLOAD_INICIADO',
  UPLOAD_CONCLUIDO = 'UPLOAD_CONCLUIDO',
  UPLOAD_FALHOU = 'UPLOAD_FALHOU',

  COMITE_CRIADO = 'COMITE_CRIADO',
  COMITE_ALTERADO = 'COMITE_ALTERADO',
  COMITE_CONCLUIDO = 'COMITE_CONCLUIDO',
  COMITE_REABERTO = 'COMITE_REABERTO',
  COMITE_REMOVIDO = 'COMITE_REMOVIDO',
  COMITE_RESTAURADO = 'COMITE_RESTAURADO',
  COLUNAS_ALTERADAS = 'COLUNAS_ALTERADAS',

  PARTICIPANTE_VINCULADO = 'PARTICIPANTE_VINCULADO',
  PARTICIPANTE_DESVINCULADO = 'PARTICIPANTE_DESVINCULADO',
  PARTICIPANTE_CRIADO = 'PARTICIPANTE_CRIADO',
  PARTICIPANTE_ALTERADO = 'PARTICIPANTE_ALTERADO',

  DISCRICIONARIO_LANCADO = 'DISCRICIONARIO_LANCADO',
  DISCRICIONARIO_ALTERADO = 'DISCRICIONARIO_ALTERADO',
  DISCRICIONARIO_ZERADO = 'DISCRICIONARIO_ZERADO',
  DISCRICIONARIO_FORA_LIMITE = 'DISCRICIONARIO_FORA_LIMITE',
  MOTIVADOR_ALTERADO = 'MOTIVADOR_ALTERADO',
  JUSTIFICATIVA_ALTERADA = 'JUSTIFICATIVA_ALTERADA',

  ATA_CADASTRADA = 'ATA_CADASTRADA',
  ATA_ALTERADA = 'ATA_ALTERADA',

  MOTIVO_CRIADO = 'MOTIVO_CRIADO',
  MOTIVO_ALTERADO = 'MOTIVO_ALTERADO',
  MOTIVO_REMOVIDO = 'MOTIVO_REMOVIDO',

  USUARIO_CRIADO = 'USUARIO_CRIADO',
  USUARIO_ALTERADO = 'USUARIO_ALTERADO',

  FILTRO_APLICADO = 'FILTRO_APLICADO',
  CONSULTA_REALIZADA = 'CONSULTA_REALIZADA',
  ERRO_PROCESSAMENTO = 'ERRO_PROCESSAMENTO',
  ACAO_FRONTEND = 'ACAO_FRONTEND',
}

/** Operação registrada na trilha (INSERT/UPDATE/SOFT_DELETE/RESTORE). */
export enum OperacaoAuditoria {
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  SOFT_DELETE = 'SOFT_DELETE',
  RESTORE = 'RESTORE',
  LOGIN = 'LOGIN',
  ERRO = 'ERRO',
}

export enum OrigemAuditoria {
  BACKEND = 'BACKEND',
  FRONTEND = 'FRONTEND',
}
